# Gradle settings
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.84

# Mod properties
mod_id=firsttorch
mod_name=First Torch
mod_license=MIT
mod_version=0.13.0-alpha.1
mod_group_id=ch.minenox.firsttorch
mod_authors=KohakuD
mod_description=First Torch is a patient, step-by-step Minecraft survival course with a native NeoForge learning interface.
